#!/usr/bin/env python3

import pop.hub
hub = pop.hub.Hub()
hub.pop.sub.add(dyne_name='pkgtools')
hub.pop.sub.add(subname="ego", pypath="ego-modules")
hub.ego.foo.sayhi("Fred")
print(hub.ego.output.red("HIYA DAWG!"))
hub.ego.plugins.sync.dosync("fasdfasdl")
# vim: ts=4 sw=4 noet
